### PR TITLE
FEATURE: Integrate optional support for CSS selector

### PR DESCRIPTION
**Pull request by jonnitto**

### CODE REVIEW

**Comment by mficzel** [comment]
Hmmm. I understand the feature but imho this makes the package more complex without any real benefit. Would like to abstain from that unless you can outline a problem this solves.

**Comment by jonnitto** [comment]
The problem is that Fusion Component builder are more frontend people. And there xpath is not very common. Of course we could ad this as a dependency, but this way, nothing would change, if it is not installed. And a CSS selector is much easier to write and read.

**Comment by jonnitto** [comment]
Comming back to this. Now I really have an issue, where I can't use an X-Path Selector, because the rendering fails…

If you want, I can show you the use case in a slack call…

**Comment by jonnitto** [comment]
Basically, it's just about the option the possibility to target elements with an id.

This could be done like that:

```php
if (empty($target)) {
    $target = '//head';
} else if (str_starts_with($target, '#')) {
    $target = '//*[@id="' . substr($target, 1) . '"]';
}
```

and if we want support plain tags (like `body`) we could extend it like that:

```php
if (empty($target)) {
    $target = '//head';
} else if (str_starts_with($target, '#')) {
    $target = '//*[@id="' . substr($target, 1) . '"]';
} else if (!str_starts_with($target, '//')) {
    $target = '//' . $target;
}
```

**Pull request closed without merging**
